// Warranty Data Generator — creates warranty-data.js with all 223 records
// Run: node generate-data.js
import { writeFileSync } from "fs";
import { fileURLToPath } from "url";
import { dirname, join } from "path";

const __dirname = dirname(fileURLToPath(import.meta.url));

function pad(n) { return String(n).padStart(3, "0"); }
function expand(base, terms) {
  return terms.map((t, i) => {
    const r = { ...base, id: `WT-${pad(base._s + i)}`, term: t.term };
    if (t.o) Object.assign(r, t.o);
    delete r._s;
    return r;
  });
}

const CD = { category:"Coating", thickness:null, installationMethod:null, hailCoverage:null, minRoofSize:null, recoverEligible:null, recoverMaxYears:null, warrantyFeePerSq:null, minWarrantyFee:null, referenceUrl:null, inspFreq:"Annual", windLimit:"Per terms" };
const SD = { category:"Single-Ply", inspFreq:"Per manufacturer specs", maintenanceRequired:"See manufacturer specs", transferPolicy:"Per manufacturer terms", warrantyFeePerSq:null, minWarrantyFee:null };

// ═══ COATINGS (WT-001 to WT-094) ═══

const c = [
  // GACO Silicone L&M (001-004)
  ...expand({ ...CD, _s:1, manufacturer:"GACO", name:"Silicone L&M NDL", membranes:["Silicone"], productLines:"GacoFlex S42, SF4200, S20, S2100, GacoRoof", warrantyName:"Labor & Material", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"NDL on leak repairs", ndl:true, inspBy:"Licensed GACO Applicator", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"Transfer fee; 60-day notice", notes:"30-day leak notification; disputes in Davidson County TN; TN law governs", strengths:["NDL on leak repairs","Ponding water NOT excluded (silicone)","Up to 20-year terms","50-yr material-only option unique in industry"], weaknesses:["Transfer fee + 60-day notice required","30-day leak notification window","Disputes governed by TN law"], bestFor:"Ponding-prone roofs needing long-term NDL coating warranty", rating:8 },
  [{term:5},{term:10},{term:15},{term:20}]),

  // GACO Silicone Material Only 50-yr (005)
  { ...CD, id:"WT-005", manufacturer:"GACO", name:"Silicone Material Only 50-yr", membranes:["Silicone"], term:50, productLines:"GacoFlex S42, SF4200, S20, S2100, GacoRoof", warrantyName:"Material Only", laborCovered:false, materialCovered:true, consequential:false, dollarCap:"Replacement product", ndl:false, inspBy:"N/A", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"Transfer fee; 60-day notice", notes:"50-year material-only unique in industry", strengths:["50-year term unique in coating industry","Ponding NOT excluded","Low-cost warranty option"], weaknesses:["No labor coverage","Material replacement only"], bestFor:"Budget projects wanting longest material guarantee available", rating:6 },

  // GACO Acrylic L&M (006-009)
  ...expand({ ...CD, _s:6, manufacturer:"GACO", name:"Acrylic L&M NDL", membranes:["Acrylic"], productLines:"GacoFlex A48, A47, A4121, A17, 127/129 Series", warrantyName:"Labor & Material", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"NDL on leak repairs", ndl:true, inspBy:"Licensed GACO Applicator", transferable:true, pondingExcluded:true, maintenanceRequired:"Yes", transferPolicy:"Transfer fee; 60-day notice", notes:"Ponding water excluded for acrylic", strengths:["NDL on leak repairs","Up to 20-year terms","Transferable"], weaknesses:["Ponding water excluded","Must use GACO licensed applicator"], bestFor:"Well-drained roofs needing acrylic restoration with NDL coverage", rating:7 },
  [{term:5},{term:10},{term:15},{term:20}]),

  // GACO Urethane L&M (010-013)
  ...expand({ ...CD, _s:10, manufacturer:"GACO", name:"Urethane L&M NDL", membranes:["Urethane"], productLines:"U91 (aromatic), U92 (aliphatic), UF90, U95", warrantyName:"Labor & Material", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"NDL on leak repairs", ndl:true, inspBy:"Licensed GACO Applicator", transferable:true, pondingExcluded:true, maintenanceRequired:"Yes", transferPolicy:"Transfer fee; 60-day notice", notes:"Ponding water excluded for urethane", strengths:["NDL on leak repairs","Urethane durability + impact resistance","Up to 20-year terms"], weaknesses:["Ponding water excluded","Must use GACO licensed applicator"], bestFor:"High-traffic roofs needing durable urethane system with NDL", rating:7 },
  [{term:5},{term:10},{term:15},{term:20}]),

  // American WeatherStar Silicone (014-017)
  ...expand({ ...CD, _s:14, manufacturer:"American WeatherStar", name:"Silicone NDL System", membranes:["Silicone"], productLines:"Silicone 410, High-Solids Silicone 412; Envir-O-Sil System", warrantyName:"NDL System (L&M)", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"NDL", ndl:true, inspBy:"Platinum/Platinum Elite Contractor", transferable:true, pondingExcluded:false, inspFreq:"Annual (contractor-performed for 20-yr)", maintenanceRequired:"Yes (annual; contractor-performed for 20-yr)", transferPolicy:"Transferable w/ inspection & approval", notes:"Third-party inspection required; renewable within 30 days of expiration; StarGard+ extension available", strengths:["NDL coverage","Ponding NOT excluded","Renewable within 30 days of expiration","StarGard+ extension available"], weaknesses:["Third-party inspection required","Must use Platinum-tier contractor","Transfer requires inspection + approval"], bestFor:"Premium silicone restoration with renewable NDL coverage", rating:9 },
  [{term:10},{term:12},{term:15},{term:20}]),

  // American WeatherStar Urethane+Silicone (018-021)
  ...expand({ ...CD, _s:18, manufacturer:"American WeatherStar", name:"Ure-A-Sil NDL System", membranes:["Urethane","Silicone"], productLines:"Ure-A-Sil System (urethane base + silicone top); Ure-A-Sil Eco", warrantyName:"NDL System (L&M)", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"NDL", ndl:true, inspBy:"Platinum/Platinum Elite Contractor", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"Transferable w/ inspection & approval", notes:"Flagship system; combines urethane strength with silicone UV/moisture resistance", strengths:["Flagship system combining urethane strength + silicone UV resistance","NDL coverage","Ponding NOT excluded (silicone topcoat)"], weaknesses:["Premium contractor tier required","Multi-coat application"], bestFor:"Maximum durability with urethane base and silicone topcoat", rating:9 },
  [{term:10},{term:12},{term:15},{term:20}]),

  // American WeatherStar Acrylic (022-024)
  ...expand({ ...CD, _s:22, manufacturer:"American WeatherStar", name:"Met-A-Gard Acrylic NDL", membranes:["Acrylic"], productLines:"Met-A-Gard (metal roof acrylic system)", warrantyName:"NDL System (L&M)", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"NDL", ndl:true, inspBy:"Platinum Contractor", transferable:true, pondingExcluded:true, maintenanceRequired:"Yes", transferPolicy:"Transferable w/ inspection & approval", notes:"Metal roof specific", strengths:["Metal roof specific system","NDL coverage","Transferable"], weaknesses:["Ponding water excluded","Metal roofs only"], bestFor:"Metal roof restoration with acrylic coating", rating:7 },
  [{term:10},{term:12},{term:15}]),

  // American WeatherStar All (025)
  { ...CD, id:"WT-025", manufacturer:"American WeatherStar", name:"Material Only (All Systems)", membranes:["Silicone","Acrylic","Urethane"], term:0, productLines:"All systems", warrantyName:"Material Only", laborCovered:false, materialCovered:true, consequential:false, dollarCap:"Replacement product", ndl:false, inspBy:"Approved Contractor", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"Transferable", notes:"Available through Approved Contractors", strengths:["Covers all chemistry types","Transferable"], weaknesses:["Material only, no labor"], bestFor:"Basic material protection across any AWS chemistry", rating:5 },

  // Sherwin-Williams UNIFLEX Silicone (026-028)
  ...expand({ ...CD, _s:26, manufacturer:"Sherwin-Williams (UNIFLEX)", name:"UNIGUARD Silicone System", membranes:["Silicone"], productLines:"Silicone22, Silicone44 Rubberized Silicone", warrantyName:"UNIGUARD System (L&M)", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"UNIFLEX Authorized Contractor", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"Per warranty terms", notes:"Backed by multi-billion dollar Sherwin-Williams; 4,600+ locations", strengths:["Backed by multi-billion dollar Sherwin-Williams","4,600+ locations nationwide","Ponding NOT excluded"], weaknesses:["Must use UNIFLEX Authorized Contractor","Dollar cap not published as NDL"], bestFor:"Owners wanting blue-chip corporate backing on coating warranty", rating:8 },
  [{term:10},{term:15},{term:20}]),

  // Sherwin-Williams UNIFLEX Acrylic (029-030)
  ...expand({ ...CD, _s:29, manufacturer:"Sherwin-Williams (UNIFLEX)", name:"UNIGUARD Acrylic System", membranes:["Acrylic"], productLines:"Premium Acrylic coatings, various formulations", warrantyName:"UNIGUARD System (L&M)", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"UNIFLEX Authorized Contractor", transferable:true, pondingExcluded:true, maintenanceRequired:"Yes", transferPolicy:"Per warranty terms", notes:"Can extend warranty with additional applications", strengths:["Sherwin-Williams corporate backing","Can extend warranty with additional applications","Transferable"], weaknesses:["Ponding water excluded","Max 15-year term for acrylic"], bestFor:"Well-drained roofs with corporate-grade warranty backing", rating:7 },
  [{term:10},{term:15}]),

  // Sherwin-Williams UNIFLEX Urethane (031-032)
  ...expand({ ...CD, _s:31, manufacturer:"Sherwin-Williams (UNIFLEX)", name:"UNIGUARD Urethane System", membranes:["Urethane"], productLines:"Urethane88 (single-component aliphatic moisture curing)", warrantyName:"UNIGUARD System (L&M)", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"UNIFLEX Authorized Contractor", transferable:true, pondingExcluded:true, maintenanceRequired:"Yes", transferPolicy:"Per warranty terms", notes:"Single-component aliphatic urethane", strengths:["Single-component aliphatic moisture curing","Sherwin-Williams backing","Transferable"], weaknesses:["Ponding water excluded","Max 15-year term"], bestFor:"Urethane restoration backed by major manufacturer", rating:7 },
  [{term:10},{term:15}]),

  // Sherwin-Williams All (033)
  { ...CD, id:"WT-033", manufacturer:"Sherwin-Williams (UNIFLEX)", name:"Material Only (All Products)", membranes:["Silicone","Acrylic","Urethane"], term:0, productLines:"All UNIFLEX products", warrantyName:"Material Only", laborCovered:false, materialCovered:true, consequential:false, dollarCap:"Replacement product", ndl:false, inspBy:"N/A", transferable:false, pondingExcluded:false, maintenanceRequired:"N/A", transferPolicy:"N/A", notes:"Product warranty per TDS: replacement of defective material when applied per instructions", strengths:["Sherwin-Williams backing","Covers all product lines"], weaknesses:["Material only","No labor coverage","Not transferable"], bestFor:"Basic material protection on UNIFLEX products", rating:4 },

  // GAF Silicone (034-036)
  ...expand({ ...CD, _s:34, manufacturer:"GAF", name:"Silicone Coating L&M", membranes:["Silicone"], productLines:"Unisil Silicone, Unisil High Solid Silicone", warrantyName:"Labor & Material", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"GAF Certified Contractor", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"Per warranty terms", notes:"Silicone over asphaltic or metal substrates; min 2 coats for Unisil; 1+ coat for High Solid", strengths:["Standard Industries backing","Ponding NOT excluded","High Solid option allows single-coat application"], weaknesses:["Must use GAF Certified Contractor","Standard Unisil requires min 2 coats"], bestFor:"Silicone restoration through established GAF contractor network", rating:8 },
  [{term:10},{term:15},{term:20}]),

  // GAF Acrylic (037-039)
  ...expand({ ...CD, _s:37, manufacturer:"GAF", name:"HydroStop Acrylic L&M", membranes:["Acrylic"], productLines:"Premium Acrylic HydroStop Top Coat, Acrylic Base/Top Coat", warrantyName:"Labor & Material", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"GAF Certified Contractor", transferable:true, pondingExcluded:true, maintenanceRequired:"Yes", transferPolicy:"Per warranty terms", notes:"20-yr available for HydroStop system; 10/15-yr for standard acrylic", strengths:["Premium HydroStop system up to 20 years","GAF/Standard Industries backing","Transferable"], weaknesses:["Ponding water excluded","Standard acrylic limited to 10/15-yr"], bestFor:"Premium acrylic restoration through GAF network", rating:8 },
  [{term:10},{term:15},{term:20}]),

  // GAF Kymax (040-042)
  ...expand({ ...CD, _s:40, manufacturer:"GAF", name:"Kymax Coating L&M", membranes:["Silicone","Acrylic"], productLines:"Kymax Coating", warrantyName:"Labor & Material", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"GAF Certified Contractor", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"Per warranty terms", notes:"Standard/Good/Better/Best warranty tiers", strengths:["Versatile silicone/acrylic blend","GAF contractor network","Transferable"], weaknesses:["Ponding coverage varies","Must use GAF Certified Contractor"], bestFor:"Flexible coating system with tiered warranty options", rating:7 },
  [{term:10},{term:15},{term:20}]),

  // Tropical (SOPREMA) Silicone (043-045)
  ...expand({ ...CD, _s:43, manufacturer:"Tropical Roofing Products (SOPREMA)", name:"Eterna-Sil Silicone System", membranes:["Silicone"], productLines:"#924 Eterna-Sil Premium Silicone, #923", warrantyName:"Full System (L&M)", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"Tropical Authorized Contractor", transferable:true, pondingExcluded:false, inspFreq:"Annual (Care & Maintenance Specs)", maintenanceRequired:"Yes (Tropical Care & Maintenance Specs)", transferPolicy:"Per warranty terms", notes:"Fully integrated into SOPREMA brand Jan 2026; 100% silicone solvent-free; Title 24 compliant; CRRC rated", strengths:["SOPREMA Group backing (integrated Jan 2026)","Can be applied over ponding water","100% silicone solvent-free","Title 24 compliant, CRRC rated"], weaknesses:["Separate warranty application per building","Must use Tropical Authorized Contractor"], bestFor:"Silicone restoration backed by global SOPREMA group", rating:8 },
  [{term:10},{term:15},{term:20}]),

  // Tropical Acrylic (046-047)
  ...expand({ ...CD, _s:46, manufacturer:"Tropical Roofing Products (SOPREMA)", name:"Acrylic System", membranes:["Acrylic"], productLines:"Various acrylic formulations", warrantyName:"Full System (L&M)", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"Tropical Authorized Contractor", transferable:true, pondingExcluded:true, maintenanceRequired:"Yes", transferPolicy:"Per warranty terms", notes:"Separate warranty application per building", strengths:["SOPREMA Group backing","Transferable"], weaknesses:["Ponding water excluded","Separate warranty per building"], bestFor:"Acrylic restoration with international manufacturer support", rating:7 },
  [{term:10},{term:15}]),

  // Tropical All (048)
  { ...CD, id:"WT-048", manufacturer:"Tropical Roofing Products (SOPREMA)", name:"Material Only (All Products)", membranes:["Silicone","Acrylic"], term:0, productLines:"All TRP products", warrantyName:"Material Only", laborCovered:false, materialCovered:true, consequential:false, dollarCap:"Replacement product", ndl:false, inspBy:"N/A", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"Per warranty terms", notes:"Limited product warranties available", strengths:["SOPREMA Group backing","Transferable"], weaknesses:["Material only","Limited coverage"], bestFor:"Basic material protection on Tropical products", rating:4 },

  // Carlisle (Henry) Silicone Gold Seal (049-051)
  ...expand({ ...CD, _s:49, manufacturer:"Carlisle (Henry)", name:"Pro-Grade 988 Gold Seal", membranes:["Silicone"], productLines:"Pro-Grade 988 Silicone (DPUR technology)", warrantyName:"Gold Seal (L&M)", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"Henry Authorized Applicator", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"Transfer available; warranty portal", notes:"CRFC products integrated into Henry; DPUR patent for dirt resistance; rain-safe in 15 min; 50+ mils single coat", strengths:["DPUR patent for dirt resistance","Rain-safe in 15 min","50+ mils single coat capability","Carlisle Companies backing"], weaknesses:["Must use Henry Authorized Applicator"], bestFor:"Premium silicone with patented dirt-resistance technology", rating:9 },
  [{term:10},{term:15},{term:20}]),

  // Henry Materials-Plus (052)
  { ...CD, id:"WT-052", manufacturer:"Carlisle (Henry)", name:"Pro-Grade 988 Materials-Plus", membranes:["Silicone"], term:15, productLines:"Pro-Grade 988 Silicone (DPUR technology)", warrantyName:"Materials-Plus (L&M)", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Materials + labor for affected areas", ndl:false, inspBy:"Henry Authorized Applicator", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"Transfer available", notes:"Covers defects; includes materials and labor to address affected areas", strengths:["Covers materials and labor for affected areas","Ponding NOT excluded","Lower cost than Gold Seal"], weaknesses:["Not full NDL","Coverage limited to affected areas"], bestFor:"Mid-tier silicone warranty with Henry's DPUR technology", rating:7 },

  // Henry Acrylic (053)
  { ...CD, id:"WT-053", manufacturer:"Carlisle (Henry)", name:"Pro-Grade 280 Acrylic Gold Seal", membranes:["Acrylic"], term:12, productLines:"Pro-Grade 280 Elastomeric White", warrantyName:"Gold Seal (L&M)", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"Henry Authorized Applicator", transferable:true, pondingExcluded:true, maintenanceRequired:"Yes", transferPolicy:"Transfer available", notes:"Water-based 100% acrylic latex; resists chalking, mildew, fungi", strengths:["Carlisle Companies backing","Resists chalking, mildew, fungi","Warranty portal"], weaknesses:["Ponding water excluded","Max 12-year term shorter than competitors"], bestFor:"Acrylic restoration with Carlisle backing where drainage is adequate", rating:6 },

  // Henry All (054)
  { ...CD, id:"WT-054", manufacturer:"Carlisle (Henry)", name:"Material Only (All Products)", membranes:["Silicone","Acrylic"], term:0, productLines:"All Pro-Grade products", warrantyName:"Material Only", laborCovered:false, materialCovered:true, consequential:false, dollarCap:"Replacement product", ndl:false, inspBy:"N/A", transferable:false, pondingExcluded:false, maintenanceRequired:"N/A", transferPolicy:"Warranty portal available", notes:"Material-only warranty notice of completion required", strengths:["Carlisle Companies backing","Warranty portal"], weaknesses:["Material only","No labor coverage"], bestFor:"Basic material protection on Henry products", rating:4 },

  // APOC (055-059)
  { ...CD, id:"WT-055", manufacturer:"APOC", name:"576 Premium Silicone Lifetime", membranes:["Silicone"], term:99, productLines:"APOC 576 Premium Silicone", warrantyName:"Material Only (product)", laborCovered:false, materialCovered:true, consequential:false, dollarCap:"Replacement product (prorated)", ndl:false, inspBy:"N/A", transferable:false, pondingExcluded:false, maintenanceRequired:"N/A", transferPolicy:"N/A", notes:"Lifetime warranty on packaging; exceeds ASTM D6694/D7281; Title 24; CRRC; rain-safe 15 min", strengths:["Lifetime material warranty unique in market","Rain-safe in 15 min","Exceeds ASTM D6694/D7281"], weaknesses:["Material only, no labor","Prorated replacement","Not transferable"], bestFor:"Budget projects wanting longest material-only silicone guarantee", rating:5 },
  { ...CD, id:"WT-056", manufacturer:"APOC", name:"258 Energy-Armor Ultra 20-yr", membranes:["Acrylic"], term:20, productLines:"APOC 258 Energy-Armor Ultra Turbo-Dri", warrantyName:"Material Only (product)", laborCovered:false, materialCovered:true, consequential:false, dollarCap:"Replacement product (prorated)", ndl:false, inspBy:"N/A", transferable:false, pondingExcluded:true, maintenanceRequired:"N/A", transferPolicy:"N/A", notes:"20-year limited warranty on packaging", strengths:["20-year material warranty on acrylic"], weaknesses:["Material only","Ponding excluded","Prorated"], bestFor:"Budget acrylic projects needing extended material coverage", rating:4 },
  { ...CD, id:"WT-057", manufacturer:"APOC", name:"246 Premium Elastomeric 12-yr", membranes:["Acrylic"], term:12, productLines:"APOC 246 Premium Elastomeric", warrantyName:"Material Only (product)", laborCovered:false, materialCovered:true, consequential:false, dollarCap:"Replacement product (prorated)", ndl:false, inspBy:"N/A", transferable:false, pondingExcluded:true, maintenanceRequired:"N/A", transferPolicy:"N/A", notes:"12-year limited warranty on packaging", strengths:["12-year material warranty"], weaknesses:["Material only","Ponding excluded","Prorated"], bestFor:"Standard acrylic material protection", rating:4 },
  { ...CD, id:"WT-058", manufacturer:"APOC", name:"264 Premium Blend", membranes:["Urethane","Acrylic"], term:10, productLines:"APOC 264 Premium Blend", warrantyName:"Material Only (product)", laborCovered:false, materialCovered:true, consequential:false, dollarCap:"Replacement product (prorated)", ndl:false, inspBy:"N/A", transferable:false, pondingExcluded:true, maintenanceRequired:"N/A", transferPolicy:"N/A", notes:"Premium blend of polyurethane and acrylic resins", strengths:["PU-Acrylic hybrid durability"], weaknesses:["Material only","Ponding excluded"], bestFor:"Budget hybrid coating with enhanced durability", rating:4 },
  { ...CD, id:"WT-059", manufacturer:"APOC", name:"System L&M Warranty", membranes:["Silicone","Acrylic","Urethane"], term:15, productLines:"All APOC products", warrantyName:"Labor & Material System", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"APOC Certified Applicator", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"30-day written notice for claims", notes:"Warranty Dept: warrantyforms@apoc.com; Founded 1913; #1 US asphalt/acrylic producer", strengths:["Full L&M system warranty","Founded 1913","Multi-chemistry options"], weaknesses:["30-day written notice for claims","Must use APOC Certified Applicator"], bestFor:"Full system coating warranty from established manufacturer", rating:7 },

  // KARNAK (060-065)
  ...expand({ ...CD, _s:60, manufacturer:"KARNAK", name:"Karna-Sil Silicone L&M", membranes:["Silicone"], productLines:"670HS Karna-Sil Ultra (high solids), 670LS Karna-Sil", warrantyName:"Material & Labor", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"Q Applicator Program", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"Per warranty terms", notes:"Pre-approval required; inspection after payment; 5-10 day processing; woman-owned certified; NSF rated potable rainwater", strengths:["Ponding NOT excluded","NSF rated for potable rainwater","Woman-owned certified"], weaknesses:["Pre-approval required","Inspection after payment","5-10 day processing"], bestFor:"Sustainability-focused projects or potable rainwater applications", rating:7 },
  [{term:10},{term:20}]),
  { ...CD, id:"WT-062", manufacturer:"KARNAK", name:"Karna-Sil Material Only", membranes:["Silicone"], term:10, productLines:"670LS Karna-Sil", warrantyName:"Material Only (product)", laborCovered:false, materialCovered:true, consequential:false, dollarCap:"Replacement product", ndl:false, inspBy:"N/A", transferable:false, pondingExcluded:false, maintenanceRequired:"N/A", transferPolicy:"N/A", notes:"10-year limited warranty on packaging", strengths:["Ponding NOT excluded","10-year product warranty"], weaknesses:["Material only","No labor coverage"], bestFor:"Basic material protection on KARNAK silicone", rating:4 },
  { ...CD, id:"WT-063", manufacturer:"KARNAK", name:"Elasto-Brite Acrylic Material Only", membranes:["Acrylic"], term:10, productLines:"501 Elasto-Brite White", warrantyName:"Material Only (product)", laborCovered:false, materialCovered:true, consequential:false, dollarCap:"Replacement product", ndl:false, inspBy:"N/A", transferable:false, pondingExcluded:true, maintenanceRequired:"N/A", transferPolicy:"N/A", notes:"10-year limited warranty on packaging", strengths:["10-year product warranty"], weaknesses:["Material only","Ponding excluded"], bestFor:"Basic acrylic material protection", rating:4 },
  ...expand({ ...CD, _s:64, manufacturer:"KARNAK", name:"Acrylic/Silicone L&M", membranes:["Acrylic","Silicone"], productLines:"Various", warrantyName:"Material & Labor", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"Q Applicator", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"Per warranty terms", notes:"Separate forms: Form 1 (metal), Form 2 (non-metal)", strengths:["Separate forms for metal vs non-metal","Up to 20-year terms","NSF rated"], weaknesses:["Smaller manufacturer","Pre-approval required"], bestFor:"Metal or non-metal substrates needing specialty coating warranty", rating:6 },
  [{term:10},{term:20}]),

  // Polyglass (066-072)
  ...expand({ ...CD, _s:66, manufacturer:"Polyglass", name:"Polybrite Silicone L&M", membranes:["Silicone"], productLines:"Polybrite PB90, PB90.1, PB95, PB95.1", warrantyName:"Labor & Material", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"Polyglass Registered Contractor", transferable:true, pondingExcluded:false, inspFreq:"Min 2x/yr per NRCA/RCMA", maintenanceRequired:"Yes (min 2x/yr per NRCA/RCMA)", transferPolicy:"$500 transfer fee + costs; 30-day notice", notes:"Separate warranty per building/system; 30-day advance notice for transfer up to 6 months post-sale", strengths:["MAPEI Group backing","Ponding NOT excluded for Polybrite","Up to 20-year terms"], weaknesses:["$500 transfer fee + costs","30-day advance notice for transfers","Semi-annual inspections required"], bestFor:"Silicone restoration backed by global MAPEI group", rating:8 },
  [{term:10},{term:15},{term:20}]),
  ...expand({ ...CD, _s:69, manufacturer:"Polyglass", name:"Acrylic Fast-Dry L&M", membranes:["Acrylic"], productLines:"Fast Drying Coatings, various", warrantyName:"Labor & Material", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"Polyglass Registered Contractor", transferable:true, pondingExcluded:true, inspFreq:"Min 2x/yr", maintenanceRequired:"Yes", transferPolicy:"$500 transfer fee + costs", notes:"Ponding water exclusion for non-silicone", strengths:["MAPEI Group backing","Fast-dry formulations","Up to 20-year terms"], weaknesses:["Ponding/lack of drainage excluded","$500 transfer fee","Semi-annual inspections"], bestFor:"Acrylic restoration with international manufacturer backing", rating:7 },
  [{term:10},{term:15},{term:20}]),
  { ...CD, id:"WT-072", manufacturer:"Polyglass", name:"Material Only (All Coatings)", membranes:["Silicone","Acrylic"], term:20, productLines:"All Polyglass coatings", warrantyName:"Material Only", laborCovered:false, materialCovered:true, consequential:false, dollarCap:"Replacement product only", ndl:false, inspBy:"Polyglass Registered Contractor", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"$500 transfer fee + costs", notes:"Excludes: pollutant discharge, testing/sampling, design errors, consequential damages, attorney fees", strengths:["MAPEI Group backing","20-year material warranty","Open Year option available"], weaknesses:["Material only","Excludes consequential damages and attorney fees","$500 transfer fee"], bestFor:"Long-term material protection on Polyglass coatings", rating:5 },

  // Everest Systems (073-081)
  ...expand({ ...CD, _s:73, manufacturer:"Everest Systems", name:"Silkoxy Silicone L&M", membranes:["Silicone"], productLines:"Silkoxy (alkoxy high-solids moisture cure silicone)", warrantyName:"Labor & Material", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"Everest Certified Applicator", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"Per warranty terms", notes:"No primer needed in most applications; Houston TX mfg facility; 100,000 sq ft production", strengths:["Alkoxy high-solids, no primer needed","Ponding NOT excluded","Houston TX manufacturing"], weaknesses:["Smaller manufacturer","Must use Everest Certified Applicator"], bestFor:"Primer-free silicone application with full L&M warranty", rating:8 },
  [{term:10},{term:15},{term:20}]),
  ...expand({ ...CD, _s:76, manufacturer:"Everest Systems", name:"EverCoat Acrylic L&M", membranes:["Acrylic"], productLines:"EverCoat, EverCoat HT (high-tensile), Fluorostar (PVDF topcoat)", warrantyName:"Labor & Material", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"Everest Certified Applicator", transferable:true, pondingExcluded:true, maintenanceRequired:"Yes", transferPolicy:"Per warranty terms", notes:"Fluorostar: 10-yr color-fast L&M warranty; plasticizer-free; water-based 100% acrylic", strengths:["Plasticizer-free formulation","High-tensile option","Fluorostar PVDF topcoat for 10-yr color-fast"], weaknesses:["Ponding water excluded","Smaller manufacturer footprint"], bestFor:"Premium acrylic with color-fast PVDF topcoat option", rating:7 },
  [{term:10},{term:15},{term:20}]),
  ...expand({ ...CD, _s:79, manufacturer:"Everest Systems", name:"EverMax/EverSol Urethane L&M", membranes:["Urethane","Polyurea"], productLines:"EverMax FR (fire-resistant polyurea), EverSol SPF", warrantyName:"Labor & Material", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"Everest Certified Applicator", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"Per warranty terms", notes:"EverMax FR for extreme weather; Eco-Level self-leveling for ponding areas", strengths:["EverMax FR for fire-resistant polyurea","Eco-Level self-leveling for ponding areas","Extreme weather protection"], weaknesses:["Specialty application required","Must use Everest Certified Applicator"], bestFor:"Extreme weather or fire-resistant coating applications", rating:8 },
  [{term:10},{term:15},{term:20}]),

  // UniCoat (082-087)
  ...expand({ ...CD, _s:82, manufacturer:"UniCoat Industrial Roofing", name:"Manufacturer Silicone L&M (via mfg)", membranes:["Silicone"], productLines:"Installs GACO, Henry Pro-Grade 988, and other mfg systems", warrantyName:"Manufacturer L&M (via mfg)", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per manufacturer warranty", ndl:false, inspBy:"UniCoat is the certified installer", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"Per manufacturer terms", notes:"CONTRACTOR, not manufacturer. 4M+ gallons installed over 20 yrs; uses GACO/Henry/other mfg warranties; 20-yr Gold Seal via Henry", strengths:["4M+ gallons installed over 20 years","Certified for multiple major mfg systems","Silicone ponding coverage via mfg warranty"], weaknesses:["Contractor, not manufacturer","Must verify which mfg warranty applies"], bestFor:"Experienced silicone coating contractor using manufacturer warranties", rating:7 },
  [{term:10},{term:15},{term:20}]),
  ...expand({ ...CD, _s:85, manufacturer:"UniCoat Industrial Roofing", name:"Manufacturer Acrylic/Urethane L&M (via mfg)", membranes:["Acrylic","Urethane"], productLines:"Installs various manufacturer systems", warrantyName:"Manufacturer L&M (via mfg)", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per manufacturer warranty", ndl:false, inspBy:"UniCoat is the certified installer", transferable:true, pondingExcluded:true, maintenanceRequired:"Yes", transferPolicy:"Per manufacturer terms", notes:"Licensed to work across US; specializes in coating installations; certified for all major systems", strengths:["Licensed across US","Certified for all major coating systems"], weaknesses:["Ponding excluded for acrylic/urethane","Warranty through manufacturer, not UniCoat"], bestFor:"National coating projects needing experienced certified installer", rating:6 },
  [{term:10},{term:15},{term:20}]),

  // FAR (088-094)
  ...expand({ ...CD, _s:88, manufacturer:"FAR (Fluid Applied Roofing)", name:"FiberSeal PU-Acrylic Hybrid L&M", membranes:["Urethane","Acrylic"], productLines:"FiberSeal Base (fiber-reinforced sprayable), ProCoat Base, ProCoat Finish", warrantyName:"Labor & Material", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"FAR Certified Contractor/Inspector", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"Renewable warranty options", notes:"Proprietary PU-Acrylic hybrid; no seam tape/fabric required; FiberSeal Base = IRE 2025 & 2026 People's Choice Award; ISO 9001-2008; dries to touch in 30 min; 20-yr requires pre-approval", strengths:["IRE People's Choice Award 2025 & 2026","PU-Acrylic hybrid resists ponding","No seam tape/fabric required","ISO 9001-2008"], weaknesses:["20-yr requires pre-approval","Newer manufacturer"], bestFor:"Innovative hybrid coating for ponding-prone roofs", rating:7 },
  [{term:10},{term:15},{term:20}]),
  ...expand({ ...CD, _s:91, manufacturer:"FAR (Fluid Applied Roofing)", name:"ProSil Silicone L&M", membranes:["Silicone"], productLines:"ProSil Alkoxy (high-solids alkoxy silicone), ProSil Finish HS", warrantyName:"Labor & Material", laborCovered:true, materialCovered:true, consequential:false, dollarCap:"Per warranty terms", ndl:false, inspBy:"FAR Certified Contractor/Inspector", transferable:true, pondingExcluded:false, maintenanceRequired:"Yes", transferPolicy:"Renewable warranty options", notes:"App rate: 10-yr = 1.75 gal/sq, 15-yr = 2.25 gal/sq, 20-yr = 2.75 gal/sq (two-coat); must be monolithic with no pinholes/voids; 20-yr requires pre-approval; app temp 41-140F", strengths:["Ponding NOT excluded","Alkoxy and high-solids options","Renewable warranty","FAR Certified Inspector program"], weaknesses:["20-yr requires pre-approval","Must use FAR Certified Contractor"], bestFor:"Silicone restoration with dedicated inspector certification program", rating:7 },
  [{term:10},{term:15},{term:20}]),
  { ...CD, id:"WT-094", manufacturer:"FAR (Fluid Applied Roofing)", name:"Material Only (FAR System)", membranes:["Silicone","Acrylic","Urethane"], term:10, productLines:"Complete FAR System (Rinseable Primer + FiberSeal Base + ProCoat/ProSil topcoats)", warrantyName:"Material Only (product)", laborCovered:false, materialCovered:true, consequential:false, dollarCap:"Replacement product", ndl:false, inspBy:"N/A", transferable:false, pondingExcluded:false, maintenanceRequired:"N/A", transferPolicy:"N/A", notes:"Product warranty: replacement of defective product; user assumes all risk; color fade not covered; FM, FBC, Miami-Dade, ASTM, CRRC certified", strengths:["FM, FBC, Miami-Dade, ASTM, CRRC certified","Multiple chemistry options"], weaknesses:["Material only","User assumes all risk","Color fade not covered"], bestFor:"Basic material protection with extensive code certifications", rating:4 },
];

console.log(`Coatings: ${c.length} records`);

// Write just coatings first, single-ply will be added in part 2
const output = JSON.stringify(c, null, 2);
writeFileSync(join(__dirname, "warranty-data-coatings.json"), output, "utf8");
console.log("Written warranty-data-coatings.json");
